services:
  transaction-db:
    image: postgres:16
    container_name: ledgerflow-transaction-db

    environment:
      POSTGRES_DB: ledgerflow_transaction
      POSTGRES_USER: ledgerflow
      POSTGRES_PASSWORD: ledgerflow

    ports:
      - "5432:5432"

    volumes:
      - transaction-db-data:/var/lib/postgresql/data

volumes:
  transaction-db-data: