spring.application.name=transaction-service

spring.datasource.url=jdbc:postgresql://localhost:5432/ledgerflow_transaction
spring.datasource.username=ledgerflow
spring.datasource.password=ledgerflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
spring.kafka.bootstrap-servers=localhost:9092