spring.application.name=ledger-service

spring.datasource.url=jdbc:postgresql://localhost:5433/ledgerflow_ledger
spring.datasource.username=ledgerflow
spring.datasource.password=ledgerflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092

server.port=8081